name: "SrLobo MQTT Bridge"
description: "Standard MQTT bridge between SrLobo Cloud and Home Assistant"
version: "0.1.1"
slug: "srlobo_mqtt_bridge"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  srlobo_token: ""
  srlobo_api_url: "https://srlobo.otomatiki.xyz"
  bootstrap_path: "/api/homeassistant/bootstrap"
  log_level: "info"

schema:
  srlobo_token: password
  srlobo_api_url: str
  bootstrap_path: str
  log_level: list(debug|info|warning|error)

map:
  - ssl:rw
